backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "/assets/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "homepage"
    label: "Homepage"
    files:
    - label: "Homepage"
      name: "home"
      file: "homepage/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Permalink", name: "permalink", widget: "string" }
        - { label: "Navigation Title", name: "navtitle", widget: "string" }
        - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
        - { label: "Body", name: "body", widget: "markdown" }

